### ISSUE TITLE
why install grub in swap partition ?

### ISSUE THREAD

**Issue by changchichung** [YasuhiroABE/ub2204-autoinstall-iso#3]
in your user-data.mbr
```
  storage:
    swap:
      size: 0
    grub:
      install_devices:
        - partition-2
    config:
      - id: root-ssd
        type: disk
        ptable: msdos
        match:
          size: largest
        wipe: superblock-recursive
        preserve: false
        grub_device: true
      - id: partition-2
        type: partition
        size: 2G
        number: 2
        device: root-ssd
        wipe: superblock
        flag: swap
        preserve: false
      - id: partition-3
        type: partition
        size: -1
        number: 3
        device: root-ssd
        wipe: superblock
        preserve: false
      - id: format-2
        type: format
        fstype: swap
        volume: partition-2
        label: SWAP
        flag: swap
        preserve: false
      - id: format-3
        type: format
        fstype: ext4
        volume: partition-3
        label: ROOT
        preserve: false
      - id: format-2-swap
        type: mount
        path: none
        device: format-2
        options: pri=1,discard=pages
      - id: format-3-root
        type: mount
        path: /
        device: format-3
        options: 'noatime,errors=remount-ro'
```
you install grub to swap partition , right ? why ? althrough this config works , but I don't understand why ?
